### ISSUE TITLE
支援区存在 鲸井小弟 情况下骰子数量增加导致识别出错的问题

### ISSUE THREAD

**Issue by Womsxd** [babalae/genius-invokation-auto-toy#1]
拿脚本挂机打周常牌的时候遇到人机使用 鲸井小弟 这张牌，该牌的作用是开局生成一点万能元素后进入对手道具牌区，然后给对手生成完成后返回自己牌区进行循环，从而导致脚本一直识别出9个骰子
14:33:02.7012|INFO|当前骰子数量9与期望的骰子数量8不相等，重试
14:33:03.3892|INFO|当前骰子状态：风 4| 岩 2| 雷 0| 草 0| 水 0| 火 2| 冰 0| 全 1

**Comment by huiyadanli** [comment]
还真是没想到的情况，看样子要加一个场景牌的识别 :joy:

**Comment by Womsxd** [comment]
看输出是有元素类型的识别，可以考虑增加一个万能元素数量判断?至少＞=1才可能有小弟

**Comment by huiyadanli** [comment]
> 看输出是有元素类型的识别，可以考虑增加一个万能元素数量判断?至少＞=1才可能有小弟

可以，这样更加准确

**Comment by huiyadanli** [comment]
1.3 版本临时解决了这个问题

**Comment by huiyadanli** [comment]
刚好遇到了一把，测试还是有些问题，暂不关闭

**Comment by huiyadanli** [comment]
修复了bug并新增了一个bug，测试通过。

但仍有小概率出现首次识别错误，识别8个（实际9个）然后正常执行，第二次识别正确后无法正常把逻辑走下去。

主要还是万能骰子识别率比较低造成的
