### ISSUE TITLE
老问题，不同表现形式

### ISSUE THREAD

**Issue by 11389698** [babalae/genius-invokation-auto-toy#10]
伐木大约20分钟（50轮）就原神客户端闪退，bgi软件没变化，上次出现该问题软件有报错，这次没报错，尝试复现后，可靠性记录如下
![image](https://github.com/babalae/genius-invokation-auto-toy/assets/79733561/2c3b2566-7532-4781-94fb-219cce5cc01f)
软件设置与版本
![image](https://github.com/babalae/genius-invokation-auto-toy/assets/79733561/7f82ffc4-757a-4865-a967-1bf8181326ff)

**Comment by 11389698** [comment]
![~2(OE}M`1 @IB%BZHY7KHE](https://github.com/babalae/genius-invokation-auto-toy/assets/79733561/1d5c80dd-e7cb-4f92-a985-051b3d7125df)
二次复现，报错代码，可靠性记录未生成记录

**Comment by 11389698** [comment]
第三次复现，电脑卡死后原神闪退，无报错，无可靠性记录

**Comment by huiyadanli** [comment]
你发错项目了

应该发这里 https://github.com/babalae/better-genshin-impact/issues

你的电脑是否是4K分辨率？

BetterGI程序的内存是否在一直增长？观察下占用
