### ISSUE TITLE
元素骰子数量不足时是否可以自动使用卡牌补充或结束回合？

### ISSUE THREAD

**Issue by rq-rn** [babalae/genius-invokation-auto-toy#2]
|ERROR|System.Exception: 骰子数量与预期不符，重试次数过多，可能出现了未知错误！

**Comment by huiyadanli** [comment]
正常逻辑下，不会出现元素投资数量不足，都是算好的行动和骰子数量的。

出现这种情况的时候，肯定前面有步骤出现问题，或者骰子被遮挡识别不出来。

**Comment by rq-rn** [comment]
嗯...我觉得不是隐藏的，看来是上一步有问题。

我在没有元素骰子的情况下试图击中技能，这是否是上一步的问题？

**Comment by huiyadanli** [comment]
是的，如果可以稳定复现，可以上传日志+对局视频

**Comment by rq-rn** [comment]
我不确定什么时候会发生这种情况，所以我会尝试记录几次。

**Comment by rq-rn** [comment]
我拍了一段视频并私下发布。
似乎有可能会在变得混乱时停止。
https://youtu.be/1KTb3k4camA
https://youtu.be/f1dTkHrD3Ls

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/genius-invokation-auto-toy/assets/15783049/d6a1481f-510a-4209-807c-d0b5fe5fe47c)


暂时不支持角色被超载、冻结、眩晕的情况，以上情况会导致后续策略无法正确进行。

对面的阵容推荐使用 莫娜、砂糖、琴 的自动策略

**Comment by rq-rn** [comment]
我会改变角色并尝试一下

**Comment by rq-rn** [comment]
打扰一下…
骰子的数量并不如预期。 重试次数太多。 可能发生了未知错误。
出现错误，是不是之前的处理有问题？
我也会附上视频
[genius-invokation-auto-toy bug report3](https://youtu.be/WzEPBNTuB0g)

**Comment by rq-rn** [comment]
哦，就是这个了。 就是这个错误。
我没有足够的骰子，但我试图在不改变角色的情况下使用技能。
[genius-invokation-auto-toy bug report4](https://youtu.be/hz851bk2ahM)

**Comment by huiyadanli** [comment]
> 打扰一下… 骰子的数量并不如预期。 重试次数太多。 可能发生了未知错误。 出现错误，是不是之前的处理有问题？ 我也会附上视频 [genius-invokation-auto-toy bug report3](https://youtu.be/WzEPBNTuB0g)

bug report3 确实是bug。等待动画的时间过短，导致认定为对方回合已经结束。然后直接进行下一步角色切换，骰子-1，可是角色切换这步执行是失败，后续骰子数量判断就错误了。

请问使用的是1.1版本吗？我记得1.1版本我对这块回合切换判定做过优化（但是可能优化的还不够彻底

**Comment by huiyadanli** [comment]
> 哦，就是这个了。 就是这个错误。 我没有足够的骰子，但我试图在不改变角色的情况下使用技能。 [genius-invokation-auto-toy bug report4](https://youtu.be/hz851bk2ahM)

被动切换角色或者当前角色无法行动的情况，都会导致策略无法继续正确执行 😂 

被动切换角色：超载、琴/砂糖技能
当前角色无法行动：冻结、被泡泡困住（水深渊法师技能）

**Comment by rq-rn** [comment]
> > 打扰一下… 骰子的数量并不如预期。 重试次数太多。 可能发生了未知错误。 出现错误，是不是之前的处理有问题？ 我也会附上视频 [genius-invokation-auto-toy bug report3](https://youtu.be/WzEPBNTuB0g)
> 
> bug report3 确实是bug。等待动画的时间过短，导致认定为对方回合已经结束。然后直接进行下一步角色切换，骰子-1，可是角色切换这步执行是失败，后续骰子数量判断就错误了。
> 
> 请问使用的是1.1版本吗？我记得1.1版本我对这块回合切换判定做过优化（但是可能优化的还不够彻底

您可能使用的是最新版本（1.2）
因为它的文件名中有1.2

**Comment by huiyadanli** [comment]
最新的1.3版本已经解决了以上大部分问题。
https://github.com/babalae/genius-invokation-auto-toy/releases/tag/1.3
现在已经能够支持被动切换角色或者当前角色无法行动的情况。

**Comment by rq-rn** [comment]
谢谢你！ ！ 感激
