### ISSUE TITLE
PVE 场地牌特殊效果导致识别出现问题

### ISSUE THREAD

**Issue by Womsxd** [babalae/genius-invokation-auto-toy#4]
轻策庄 小白 七圣召唤PVE场地牌特殊效果

12:23:08.3853|INFO|当前骰子状态：风 0| 岩 2| 雷 0| 草 0| 水 0| 火 0| 冰 0| 全 4 
12:23:09.3969|INFO|当前骰子数量6与期望的骰子数量5不相等，重试

![image](https://github.com/babalae/genius-invokation-auto-toy/assets/45663319/cc74aede-72ed-4e51-b00f-41418b4e13d5)

**Comment by huiyadanli** [comment]
这个难搞了。暂时不会判断敌方死亡状态。

我准备搞个共享文档，记录下一些无法支持，或者完全打不过的冒险挑战/角色邀约/每周来客对局。

**Comment by Womsxd** [comment]
给个选项？当这个选项启用时在对局内多次识别与预期有误的时候以识别为准

**Comment by huiyadanli** [comment]
可以，多次判断一致后以此结果为准，单次错误率太高了

**Comment by huiyadanli** [comment]
![image](https://github.com/babalae/genius-invokation-auto-toy/assets/15783049/84577651-9f0d-41a4-ae6d-6ab4cb8eea69)

重试N次后失败，匹配此处图片（非文字），如果不是8，取前面重试中命中最多的结果

如果实际可行，#1 也将使用这个方案

**Comment by huiyadanli** [comment]
已经在 https://github.com/babalae/better-genshin-impact/issues/14 解决，但未测试。

新版本：https://github.com/babalae/better-genshin-impact/releases/tag/0.14.0

但是OCR方案还是存在识别不出来的情况，有待继续优化。

有问题在 better-genshin-impact 下新开 issue 讨论
